### ISSUE TITLE
about pyflow 

### ISSUE THREAD

**Issue by HymEric** [alterzero/RBPN-PyTorch#1]
Can u tell me how to ues pyflow? And I cannot install pflow correctly.

**Comment by alterzero** [comment]
It is available in their page https://github.com/pathak22/pyflow
"
git clone https://github.com/pathak22/pyflow.git
cd pyflow/
python setup.py build_ext -i
python demo.py    # -viz option to visualize output
"

**Comment by Shawf** [comment]
@alterzero ，I have installed the pyflow as you said， but when i train the model， sometimes it still has error———“All the pixels are invalid in estimation Laplacian noise”， sometimes it doesnt have the error
