### ISSUE TITLE
CUDA out of memory when training 

### ISSUE THREAD

**Issue by se11en** [alterzero/RBPN-PyTorch#12]
I'm using a RTX2060 GPU, apparently the memory of it is not enough( 6 GiB) .

What's the lowest capacity to train RBPN? I noticed that  you used 2 GPUS with video memory of 16GiB totally. But I can only afford a 8GiB one, is 8GiB available? or is there other ways to solve this problem so that I can train on a RTX2060?

thanks a lot,

a noob

**Comment by alterzero** [comment]
You can try to use fewer neighbor frames (nFrames) and lower training patches (patch_size).
For example: set nFrames = 5 and patch_size=48
