### ISSUE TITLE
Why didn't rescale flow into (0,1) by default?

### ISSUE THREAD

**Issue by babyformula** [alterzero/RBPN-PyTorch#17]
Hi, thanks for sharing.

There's a doubt when training about the function get_flow(). I got the three model inputs (img, neighbor, flow), of which the img and the neighbor seems valued between (0,1). But the flow concatenated by u,v seems almost (3.xxx, 9.xxx ), and also the rescale_flow function is commented by default.

It would be appreciated if you could like share the related thoughts. Thanks

**Comment by alterzero** [comment]
I noticed this as well. 
It’s a difficult question in case of optical flow and might need more investigation.

I have tried to rescale the flow into [-1,1] where max and min displacement are 40,-40.
Basically the max and min displacement should be calculated for whole batch to prevent losing some scales. However, the results are substantially the same with the current approach (without rescale).
