### ISSUE TITLE
Pretrained on other dataset?

### ISSUE THREAD

**Issue by mangdian** [alterzero/RBPN-PyTorch#18]
I notice that the code load a pretrained weight file. Which dataset is the model pretrained on? What's the performance on Vimeo90K without pretraining?

**Comment by alterzero** [comment]
The code provides the possibility to train the network using pretrained model.
This function can also be used to continue training process. 
For example, you stop the training on epoch 15. You can continue training by set "--pretrained_sr" and "--start_epoch 15"

On our training, we only use vimeo90k from scratch.
