### ISSUE TITLE
one memo 

### ISSUE THREAD

**Issue by HymEric** [alterzero/RBPN-PyTorch#2]
in rbon.py, there is a correction in line 90: it should be

feat_frame.append(self.feat1(torch.cat((x.float(), neigbor[j].float(), flow[j].float()), 1)))

**Comment by alterzero** [comment]
Thank you.
But not sure if it is necessary, because flow, x, and neighbor should be a float.

**Comment by musicrainie** [comment]
In my case, the eval.py cannot run until changing "return flow" to "return flow.astype(np.float32)"

https://github.com/alterzero/RBPN-PyTorch/blob/08757cb463a46a4dccb7f28d8bbf1ef8e21ea2a6/dataset.py#L98
