### ISSUE TITLE
About  the size of patch size and frame

### ISSUE THREAD

**Issue by MuZiGuYue** [alterzero/RBPN-PyTorch#22]
Hello, @alterzero , thanks for your excellent work! I have some questions about the training phase.

1. The LR image in the Vimeo-90k dataset  is 112*24, and you set the patch size to 64 while training. How to set the patch size if I train the RBPN network using 480*270 LR images?
2. In your training code, if the target frame is the last frame of the video, you set the future neighbor frames as the target frame and the flow between these frames and target frame will be zero. I want to know if some potential problems will occur while concatenating the frames and flow.

Thanks and hope your reply.

**Comment by alterzero** [comment]
Hi,

1. I don't really understand the question, but it should work as long as your LR images has at least 64x64 pixels. Even not, you can set smaller patches for example 48x48
2. In the training, we use middle frame on vimeo90k, so the last frame was never used in the training. In testing, this case is inevitable. However, RBPN still works with this setup. Another solution is to change the setting to "previous frames" only when the target is the last frame.

**Comment by MuZiGuYue** [comment]
Thank you for your reply.

For the first question, what I want to say is that the LR image size in my training set is 480x270, so how much should the patch size be set?

Thanks again.

**Comment by alterzero** [comment]
I'm not sure, but if you have enough GPU memory, you can try 96x96.
Basically larger patch may improve the performance, since larger context is used.
But the improvement might not substantial.
