### ISSUE TITLE
Something wrong in dataset.py

### ISSUE THREAD

**Issue by ABadCandy** [alterzero/RBPN-PyTorch#25]
wrong with Line74 in dataset.py: seq = [x for x in range(4-tt,5+tt) if x!=4] 
if nFrames=11 and tt=int(nFrames/2)=5, seq will start from -1, however, there isn't im"-1".png .

**Comment by alterzero** [comment]
The F11 model was used for NTIRE2019.
It was not trained and tested on vimeo90k, but on NTIRE2019 dataset for video SR challenge.
But you can use this model for Vid4 or SPMCS dataset.
