### ISSUE TITLE
questions about generalization

### ISSUE THREAD

**Issue by splinter21** [alterzero/RBPN-PyTorch#26]
For example, one short video, 1-10 frames are in scene 1, 11-20 frames are in scene 2.
So there are two situations(using future=True, nFrames=7):
1>1-3 lack of previous neibors， and 17-20 lack of future neibors. Replace input LR as the lack neibors, and the flow is zero. 
2>for 7-13, the neighbors cross two scene, and the flows are disorderly.
Will the network be well generalized in these two situations when testing? If not, how to solve these two problems?

I looked at the training set you used. There is no situation 2, because every pairs are 7 frames from the same scene.
If I cut the video into different scenes, situation 2 ↓，but situation 1 ↑.

**Comment by splinter21** [comment]
I looked at the training set you used. There is no situation 2, because every pairs are 7 frames from the same scene.

**Comment by splinter21** [comment]
If I cut the video into different scenes, situation 2 ↓，but situation 1 ↑.

**Comment by alterzero** [comment]
You can check our paper (Table 5), it shows that RBPN still works with random temporal order.
However, you can also change the setting to "future frame only" for frame 1-3 and "previous frames only" for frame 17-20, avoiding the zero flow images

**Comment by musicrainie** [comment]
> For example, one short video, 1-10 frames are in scene 1, 11-20 frames are in scene 2.
> So there are two situations(using future=True, nFrames=7):
> 1>1-3 lack of previous neibors， and 17-20 lack of future neibors. Replace input LR as the lack neibors, and the flow is zero.
> 2>for 7-13, the neighbors cross two scene, and the flows are disorderly.
> Will the network be well generalized in these two situations when testing? If not, how to solve these two problems?
> 
> I looked at the training set you used. There is no situation 2, because every pairs are 7 frames from the same scene.
> If I cut the video into different scenes, situation 2 ↓，but situation 1 ↑.

For the situation 2, I think scene-cutting the input sequence as a preprocessing step is necessary.
