### ISSUE TITLE
About testing on my own imgs

### ISSUE THREAD

**Issue by Gavin666Github** [alterzero/RBPN-PyTorch#28]
Great Job , thank you! I'am very interesting on your work.
 And I have a question to ask, when we do the testing, the input img is based on the sampling of the original image. Now I do not have the original image, only the low-quality image. 
Assuming that I only have 7 consecutive low-resolution images, no corresponding high-definition original image, how should I synthesize a high-quality image? Look forward to your reply！

**Comment by alterzero** [comment]
I'm planning to add test script for the LR input images.
Actually it is not that difficult to do, you can just removing the "resize" function in the load_img function (dataset.py)

**Comment by Gavin666Github** [comment]
@alterzero yes,Thank you very much!

**Comment by gittigxuy** [comment]
@alterzero,@Gavin666Github,I have tried this method ,but could not get the SR picture,could you please illustrate detailly?

**Comment by crypticsymmetry** [comment]
@gittigxuy did you ever figure this out? i would like to do this as well.
