### ISSUE TITLE
How to predict the first frame or last frame of a video

### ISSUE THREAD

**Issue by sjf18** [alterzero/RBPN-PyTorch#30]
Thanks for your great work!
I have a question that how to predict the first or the last frames that no former or latter frames?
In your work, it seems you use neighbor frames around the key frames to help predict the target frame.

**Comment by alterzero** [comment]
In the paper, specifically Table 4, you can change the setup.
For example, on the last frame, you can change the context using only previous frames.
There are performance drop but not significant.
