### ISSUE TITLE
Something severely wrong happened!!! All the pixels are invalid in estimation Laplacian noise!!!

### ISSUE THREAD

**Issue by Magic-chao** [alterzero/RBPN-PyTorch#32]
It really comfuse me!  I have passed the pyflow demo and also use python3.5.
But I have the same error above. How can I solve this problem?

**Comment by alterzero** [comment]
I will recheck this issues again.
Looks like there is compatibility issue with pyflow.
Otherwise, you can just retrained the network using other optical flow algorithm, for example the one in opencv.
