### ISSUE TITLE
The test results of the picture are not clear

### ISSUE THREAD

**Issue by zhangxiaopang88** [alterzero/RBPN-PyTorch#34]
Hello, thank you very much for your code, I use your test code, found that the test results are more blurred than the original, and print the following information, can you give me some suggestions？

Something severely wrong happened!!!
All the pixels are invalid in estimation Laplacian noise!!!
Something severely wrong happened!!!
All the pixels are invalid in estimation Laplacian noise!!!
Something severely wrong happened!!!
All the pixels are invalid in estimation Laplacian noise!!!
Something severely wrong happened!!!
All the pixels are invalid in estimation Laplacian noise!!!
Something severely wrong happened!!!
All the pixels are invalid in estimation Laplacian noise!!!
Something severely wrong happened!!!

===> Processing: 47 || Timer: 0.2439 sec.

**Comment by Suyuanhang** [comment]
Yes, me the same. But the reconstructed image is naturally more blurred than the original, this makes sense.

**Comment by alterzero** [comment]
I think the flow map somehow might be corrupted since you have those errors.
Unfortunately, I still have no time to investigate it.
What I can tell you now is that I used python 3.5.2 to compile the pyflow source.
