### ISSUE TITLE
could you share the code to train luminance channel,not RGB channel?

### ISSUE THREAD

**Issue by gittigxuy** [alterzero/RBPN-PyTorch#35]
Thanks

**Comment by alterzero** [comment]
You can do it.
Basically, you can change num_channels=1

**Comment by gittigxuy** [comment]
No,I do not think so,just change num_channels=1,so could you please release a detail example code to train luminance channel data?Thanks

**Comment by alterzero** [comment]
Of course you need to convert the train image to luminance only beforehand.

Anyhow, I did not train the network using only luminance channel, but only the evaluation is calculated the PSNR using luminance layer only.

**Comment by gittigxuy** [comment]
So,if I train RGB data,and test with luminance  channel,does the result same with both Train and Test use  luminance  channel
