### ISSUE TITLE
is this what training is supposed to look like? will also randomly get "all the pixels are invalid...."

### ISSUE THREAD

**Issue by crypticsymmetry** [alterzero/RBPN-PyTorch#36]
it will randomly say "All the pixels are invalid in estimation Laplacian noise" while training. is it okay?

mostly the training looks like this.
.....................................................................
Pyramid level 2
Pyramid level 1
Pyramid level 0
Constructing pyramid...done!
Pyramid level 2
Pyramid level 1
Pyramid level 0
Constructing pyramid...done!
Pyramid level 2
Pyramid level 1
Pyramid level 0
Constructing pyramid...done!
Pyramid level 2
Pyramid level 1
Pyramid level 0
===> Epoch[1](327/64612): Loss: 13.6273 || Timer: 0.1491 sec.

**Comment by alterzero** [comment]
Don't forget to set bool OpticalFlow::IsDisplay=false (pyflow/src/OpticalFlow.cpp) to remove the "Pyramid level" text.

By having that error, I assume your flow map is not accurate.
But until now I have no time to investigate the pyflow.
I can only say you need to use Python 3.5.2 to compile it.
