### ISSUE TITLE
Some question about testing on windows without GPU（CUDA）

### ISSUE THREAD

**Issue by dushide** [alterzero/RBPN-PyTorch#40]
Thank you for making your code public. Can your code be reproduced on a CPU basis, and how to do it. Because I had this problem during testing:

Exception: No GPU found, please run without --cuda.

Looking forward to your reply.

**Comment by se11en** [comment]
With 8 GPUS， you have to train the model for over a week to reach convergence. With on cpu it would be too long to train this model (probably longer than 1 or 2 month).

**Comment by dushide** [comment]
Thank you for your reply. I understand. It is of great help to me.
