### ISSUE TITLE
Bug in dataset.py?

### ISSUE THREAD

**Issue by coolKeen** [alterzero/RBPN-PyTorch#6]
Hi, thanks for your nice code!
In line 53 of dataset.py, I think the code should be 
"
if nFrames%2 == 0:
    seq = [x for x in range(-tt,tt) if x!=0] # or seq = [x for x in range(-tt+1,tt+1) if x!=0]
else:
    seq = [x for x in range(-tt,tt+1) if x!=0]
"
because when nFrames is an even number, " seq = [x for x in range(-tt,tt+1) if x!=0]" will make the number of neigbor equal to nFrames instead of nFrames-1.
You can try running the command "python main.py  --other_dataset True --nFrames 6".

**Comment by alterzero** [comment]
Thank you, I just revised that part.

**Comment by musicrainie** [comment]
And so, for the same reason, should the following line
https://github.com/alterzero/RBPN-PyTorch/blob/08757cb463a46a4dccb7f28d8bbf1ef8e21ea2a6/dataset.py#L74
be changed to "seq = [x+4 for x in range(-tt, tt+(0 if (nFrames % 2 ==0) else 1)) if x!=0]" or something?
