### ISSUE TITLE
Problem with skimage

### ISSUE THREAD

**Issue by RuyiLuo** [alterzero/RBPN-PyTorch#8]
Hi,

I successfully run follows:
>  python setup.py build_ext -i 
>  cp pyflow*.so ..

When I try to run

> python main.py 

I encounter a problem about skimage

> Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from data import get_training_set, get_eval_set
  File "/home/ryluo/Desktop/RBPN-PyTorch/data.py", line 7, in <module>
    from dataset import DatasetFromFolderTest, DatasetFromFolder
  File "/home/ryluo/Desktop/RBPN-PyTorch/dataset.py", line 10, in <module>
    from skimage import img_as_float
ModuleNotFoundError: No module named 'skimage'

Any ideas what causing this probelm?

**Comment by alterzero** [comment]
as in the error, you need to install "skiimage"

pip install scikit-image

**Comment by RuyiLuo** [comment]
> as in the error, you need to install "skiimage"
> 
> pip install scikit-image

Thanks for your replies.
Ye, I solve this problem yesterday, by google.

However, the Vimeo-90k Dataset is too large, how do you download it?

**Comment by alterzero** [comment]
Don't use browser. 
If you use linux, download it using wget might be better, and use background process.

nohup wget http://data.csail.mit.edu/tofu/dataset/vimeo_septuplet.zip &

**Comment by RuyiLuo** [comment]
> Don't use browser.
> If you use linux, download it using wget might be better, and use background process.
> 
> nohup wget http://data.csail.mit.edu/tofu/dataset/vimeo_septuplet.zip &

OK, I get it.
Thanks!
