### ISSUE TITLE
About PIL mirror() and flip() in dataset/augment()

### ISSUE THREAD

**Issue by musicrainie** [alterzero/RBPN-PyTorch#9]
According to the Pillow Docs, 'PIL.ImageOps.mirror(image)' flips image horizontally (left to right) and 'PIL.ImageOps.flip(image)' flips the image vertically (top to bottom). So maybe a misusage exists in 
https://github.com/alterzero/RBPN-PyTorch/blob/08757cb463a46a4dccb7f28d8bbf1ef8e21ea2a6/dataset.py#L136

**Comment by alterzero** [comment]
This function is to perform data augmentation during training, and it is not use during testing.
